spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: db1
    password: db1234
  thymeleaf:
    cache: false  # 页面热部署 即页面修改后立即生效

# following text is .properties file config
#    spring.datasource.url=jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true
#    spring.datasource.username=root
#    spring.datasource.password=root





